import { DataTypes } from 'sequelize';
import { Migration } from '../src/migrate';

export const up: Migration = async ({ context: sequelize }) => {
  await sequelize.getQueryInterface().createTable('token', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      allowNull: false,
      primaryKey: true,
    },
    token: {
      type: DataTypes.STRING(126),
      allowNull: false,
    },
    repeat: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    randomRevertRate: {
      type: DataTypes.INTEGER,
      allowNull: false,
      field: 'random_revert_rate',
    },
    type: {
      type: DataTypes.ENUM('plus', 'minus', 'plusAndMinus'),
      allowNull: false,
    },
    set: {
      type: DataTypes.STRING(126),
      allowNull: true,
    }
  });

  await sequelize.getQueryInterface().bulkInsert('token', [
    {token: '+', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'symbol'},
    {token: '-', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'symbol'},
    {token: '±', repeat: 10, random_revert_rate: 0, type: 'plusAndMinus', set: 'symbol'},
    {token: '+-', repeat: 1, random_revert_rate: 0, type: 'plusAndMinus', set: 'symbol'},
    {token: '-+', repeat: 1, random_revert_rate: 0, type: 'plusAndMinus', set: 'symbol'},

    {token: '👍', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '👍🏻', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '👍🏼', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '👍🏽', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '👍🏾', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '👍🏿', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '😀', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '😃', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '😄', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '😁', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '🤟', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '👏', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '💪', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '❤️', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '😍', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},
    {token: '😘', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'emoji'},

    { token: '👎', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'emoji'},
    { token: '👎🏻', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'emoji'},
    { token: '👎🏼', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'emoji'},
    { token: '👎🏽', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'emoji'},
    { token: '👎🏾', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'emoji'},
    { token: '👎🏿', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'emoji'},
    { token: '💩', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'emoji'},
    { token: '😡', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'emoji'},
    { token: '🤬', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'emoji'},
    { token: '🙁', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'emoji'},
    { token: '🤢', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'emoji'},
    { token: '🤮', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'emoji'},
    { token: '🖕', repeat: 10, random_revert_rate: 0, type: 'minus', set: 'emoji'},

    {token: '🤣', repeat: 10, random_revert_rate: 10, type: 'plus', set: 'random_emoji'},
    {token: '😂', repeat: 10, random_revert_rate: 10, type: 'plus', set: 'random_emoji'},
    {token: '😆', repeat: 10, random_revert_rate: 10, type: 'plus', set: 'random_emoji'},
    {token: '🤩', repeat: 10, random_revert_rate: 30, type: 'plus', set: 'random_emoji'},
    {token: '🤪', repeat: 10, random_revert_rate: 50, type: 'plus', set: 'random_emoji'},
    {token: '😳', repeat: 10, random_revert_rate: 50, type: 'plus', set: 'random_emoji'},
    {token: '🥴', repeat: 10, random_revert_rate: 50, type: 'plus', set: 'random_emoji'},
    {token: '🤯', repeat: 10, random_revert_rate: 25, type: 'minus', set: 'random_emoji'},
    {token: '🤡', repeat: 10, random_revert_rate: 30, type: 'minus', set: 'random_emoji'},
    {token: '👿', repeat: 10, random_revert_rate: 10, type: 'minus', set: 'random_emoji'},
    {token: '😱', repeat: 10, random_revert_rate: 25, type: 'minus', set: 'random_emoji'},
    {token: '😲', repeat: 10, random_revert_rate: 25, type: 'minus', set: 'random_emoji'},
    {token: '😧', repeat: 10, random_revert_rate: 25, type: 'minus', set: 'random_emoji'},
    {token: '😦', repeat: 10, random_revert_rate: 25, type: 'minus', set: 'random_emoji'},


  { token: 'лайк', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'ня', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'няшно', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'заебись', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'збс', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'клас', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'класс', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'классно', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'огонь', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'агонь', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'круто', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'крутяк', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'пиздато', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'ахуенно', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'ахуено', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'ахуена', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'ахуенна', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'плюс', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'хорошо', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'плюсую', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'дико плюсую', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'хаха', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'ахах', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'хахах', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'ахаха', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'хахаха', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'ахахах', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'хахахах', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'охуенно', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'ору', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'орно', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'орнул', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'каеф', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'спасибо', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'спс', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'благодарю', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'найс', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'пожалуйста', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'кек', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'лол', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'топ', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'отлично', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'гениально', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'шикарно', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},
  { token: 'прикольно', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'ru'},

  { token: 'дизлайк', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'говно', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'гавно', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'хуйня', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'отстой', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'кринж', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'хуево', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'хуёво', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'фу', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'фуу', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'фууу', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'фуууу', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'фууууу', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'бе', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'бее', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'беее', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'бееее', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'беееее', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'минус', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},
  { token: 'плохо', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'ru'},

  { token: 'like', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'en'},
  { token: 'top', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'en'},
  { token: 'nice', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'en'},
  { token: 'cool', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'en'},
  { token: 'kek', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'en'},
  { token: 'lol', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'en'},
  { token: 'dislike', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'en'},

  { token: 'сыр', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: 'nya', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: 'сырно', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: 'класека', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: 'классека', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: 'класика', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: 'классика', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: 'золото', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: 'платина', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: 'космос', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: 'ор', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: 'ор выше гор', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: 'орево', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: 'у меня встал', repeat: 1, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},
  { token: ')', repeat: 10, random_revert_rate: 0, type: 'plus', set: 'intellectuals'},

  { token: 'мда', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'intellectuals'},
  { token: 'мдаа', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'intellectuals'},
  { token: 'мдааа', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'intellectuals'},
  { token: 'тугосерно', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'intellectuals'},
  { token: '(', repeat: 1, random_revert_rate: 0, type: 'minus', set: 'intellectuals'},
  ]);

};

export const down: Migration = async ({ context: sequelize }) => {
  await sequelize.getQueryInterface().dropTable('token');
};
