// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ru'

export type Locales =
	| 'ru'
	| 'ru-int'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	bot: {
		/**
		 * Кажется что-то сломалось(
		 */
		error: string
		/**
		 * Супертоп
		 */
		supertop: string
		/**
		 * Топ
		 */
		top: string
		/**
		 * Антитоп
		 */
		bottom: string
		/**
		 * Топ пуст. Клёвых сообщений не было(
		 */
		topEmpty: string
		/**
		 * Нельзя меня оценивать!
		 */
		banMeRate: string
		/**
		 * Отстань от бота! Оценивать можно только людей
		 */
		banBotRate: string
		/**
		 * Оценивать можно не чаще раза в минуту
		 */
		banFrequency: string
		/**
		 * Плюс к антирейтингу
		 */
		minusAction: string
		/**
		 * Плюс к рейтингу
		 */
		plusActin: string
		/**
		 * Плюс к рейтингу и антирейтингу
		 */
		plusMinusAction: string
	}
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: string }) => LocalizedString
	bot: {
		/**
		 * Кажется что-то сломалось(
		 */
		error: () => LocalizedString
		/**
		 * Супертоп
		 */
		supertop: () => LocalizedString
		/**
		 * Топ
		 */
		top: () => LocalizedString
		/**
		 * Антитоп
		 */
		bottom: () => LocalizedString
		/**
		 * Топ пуст. Клёвых сообщений не было(
		 */
		topEmpty: () => LocalizedString
		/**
		 * Нельзя меня оценивать!
		 */
		banMeRate: () => LocalizedString
		/**
		 * Отстань от бота! Оценивать можно только людей
		 */
		banBotRate: () => LocalizedString
		/**
		 * Оценивать можно не чаще раза в минуту
		 */
		banFrequency: () => LocalizedString
		/**
		 * Плюс к антирейтингу
		 */
		minusAction: () => LocalizedString
		/**
		 * Плюс к рейтингу
		 */
		plusActin: () => LocalizedString
		/**
		 * Плюс к рейтингу и антирейтингу
		 */
		plusMinusAction: () => LocalizedString
	}
}

export type Formatters = {}
